# Generated by Django 3.2.16 on 2023-01-28 23:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20230129_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrow',
            name='ref',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ref',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
