# Generated by Django 3.2.16 on 2023-01-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20230129_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrow',
            name='ref',
            field=models.UUIDField(default='d36e782a9c294191805a25d4888c7c48', editable=False, unique=True),
        ),
    ]
