# Generated by Django 3.2.16 on 2023-01-29 12:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_escrow_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrow',
            name='ref',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
